name: Minimize and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DO_SPACES_KEY }}
          aws-secret-access-key: ${{ secrets.DO_SPACES_SECRET }}
          aws-region: us-west-1

      - name: Upload /assets/ files to DigitalOcean Space root
        env:
          SPACE_NAME: cdn-reallygreatads
          SPACE_REGION: sfo3
        run: |
          aws s3 cp dist/assets/ s3://${SPACE_NAME}/ --recursive --region ${SPACE_REGION} --endpoint https://${SPACE_REGION}.digitaloceanspaces.com --acl public-read

      - name: Install DigitalOcean CLI
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.91.0/doctl-1.91.0-linux-amd64.tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin

      - name: Purge Cache for files in root
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
        run: |
          CDN_ID=$(doctl compute cdn list --no-header --format ID)
          FILES_TO_PURGE=$(aws s3 ls s3://${SPACE_NAME}/ --recursive | awk '{print $4}')
          for file in $FILES_TO_PURGE; do
            doctl compute cdn flush $CDN_ID --files /$file
          done
